version: "3.5"
services:
  postgres:
    container_name: netguru-postgres
    image: postgres:13-alpine
    command: postgres -c 'max_connections=250'
    ports:
      - 21432:5432
    environment:
      POSTGRES_USER: ${PGUSER:-netguru}
      POSTGRES_PASSWORD: ${PGPASSWORD:-netguru}
      POSTGRES_DB: ${PGPGDATABASE:-netguru}
